#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassPurchaseScreen

#include "Basic.hpp"

#include "BattlePassPurchaseScreen_classes.hpp"
#include "BattlePassPurchaseScreen_parameters.hpp"


namespace SDK
{

// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.BndEvt__BattlePassPurchaseScreen_Button_ConfirmBundle_K2Node_ComponentBoundEvent_1_OnVisibilityChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::BndEvt__BattlePassPurchaseScreen_Button_ConfirmBundle_K2Node_ComponentBoundEvent_1_OnVisibilityChangedEvent__DelegateSignature(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__BattlePassPurchaseScreen_Button_ConfirmBundle_K2Node_ComponentBoundEvent_1_OnVisibilityChangedEvent__DelegateSignature");

	Params::BattlePassPurchaseScreen_C_BndEvt__BattlePassPurchaseScreen_Button_ConfirmBundle_K2Node_ComponentBoundEvent_1_OnVisibilityChangedEvent__DelegateSignature Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.BndEvt__BattlePassPurchaseScreen_Button_ToCrew_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::BndEvt__BattlePassPurchaseScreen_Button_ToCrew_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__BattlePassPurchaseScreen_Button_ToCrew_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::BattlePassPurchaseScreen_C_BndEvt__BattlePassPurchaseScreen_Button_ToCrew_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBattlePassPurchaseScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPurchaseScreen_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPurchaseScreen_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.EventScreenTransitionIn
// (BlueprintCallable, BlueprintEvent)

void UBattlePassPurchaseScreen_C::EventScreenTransitionIn()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EventScreenTransitionIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.ExecuteUbergraph_BattlePassPurchaseScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::ExecuteUbergraph_BattlePassPurchaseScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BattlePassPurchaseScreen");

	Params::BattlePassPurchaseScreen_C_ExecuteUbergraph_BattlePassPurchaseScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.Finished_606B179748E26374BE50B49D16BB56C8
// (BlueprintCallable, BlueprintEvent)

void UBattlePassPurchaseScreen_C::Finished_606B179748E26374BE50B49D16BB56C8()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Finished_606B179748E26374BE50B49D16BB56C8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnDownloadBackgroundComplete
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UTexture2D*                       NewBackground                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::OnDownloadBackgroundComplete(class UTexture2D* NewBackground)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnDownloadBackgroundComplete");

	Params::BattlePassPurchaseScreen_C_OnDownloadBackgroundComplete Parms{};

	Parms.NewBackground = NewBackground;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnPurchaseConfirmed
// (Event, Protected, BlueprintEvent)

void UBattlePassPurchaseScreen_C::OnPurchaseConfirmed()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPurchaseConfirmed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnPurchaseStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EBattlePassPurchaseState                InCurrentState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::OnPurchaseStateChanged(EBattlePassPurchaseState InCurrentState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPurchaseStateChanged");

	Params::BattlePassPurchaseScreen_C_OnPurchaseStateChanged Parms{};

	Parms.InCurrentState = InCurrentState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnSetNavButtonNotificationText
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             NotificationText                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBattlePassPurchaseScreen_C::OnSetNavButtonNotificationText(const class FText& NotificationText)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnSetNavButtonNotificationText");

	Params::BattlePassPurchaseScreen_C_OnSetNavButtonNotificationText Parms{};

	Parms.NotificationText = std::move(NotificationText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnSetScreenInteractable
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInteractable                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::OnSetScreenInteractable(bool bInteractable)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnSetScreenInteractable");

	Params::BattlePassPurchaseScreen_C_OnSetScreenInteractable Parms{};

	Parms.bInteractable = bInteractable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnShowNavButtonNotification
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShowNotification                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::OnShowNavButtonNotification(const bool bShowNotification)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnShowNavButtonNotification");

	Params::BattlePassPurchaseScreen_C_OnShowNavButtonNotification Parms{};

	Parms.bShowNotification = bShowNotification;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.OnStartingDownloadBackground
// (Event, Protected, BlueprintEvent)

void UBattlePassPurchaseScreen_C::OnStartingDownloadBackground()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnStartingDownloadBackground");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPurchaseScreen_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::BattlePassPurchaseScreen_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.SetDesignTimeImages
// (BlueprintCallable, BlueprintEvent)

void UBattlePassPurchaseScreen_C::SetDesignTimeImages()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetDesignTimeImages");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.SetMobileVisuals
// (Public, BlueprintCallable, BlueprintEvent)

void UBattlePassPurchaseScreen_C::SetMobileVisuals()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMobileVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPurchaseScreen.BattlePassPurchaseScreen_C.__c4523620-44af-d218-7add-b3bcf9bc0731_SourceToDest
// (Final, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBattlePassPurchaseScreen_C::__c4523620_44af_d218_7add_b3bcf9bc0731_SourceToDest() const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("__c4523620-44af-d218-7add-b3bcf9bc0731_SourceToDest");

	Params::BattlePassPurchaseScreen_C___c4523620_44af_d218_7add_b3bcf9bc0731_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

