#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPS28_LandingPageButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BattlePassBase_structs.hpp"
#include "CommonInput_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.ConvertWhiteTextToHoveredColor
// 0x0020 (0x0020 - 0x0000)
struct BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor final
{
public:
	bool                                          Hover;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_8;                              // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_2;                           // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor");
static_assert(sizeof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor) == 0x000020, "Wrong size on BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Hover) == 0x000000, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Hover' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable) == 0x000001, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_1) == 0x000002, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_2) == 0x000003, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_3) == 0x000004, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_4) == 0x000005, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_bool_Variable) == 0x000010, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, CallFunc_GetCurrentInputType_ReturnValue) == 0x000011, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_5) == 0x000012, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, K2Node_Select_Default) == 0x000013, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_6) == 0x000014, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_bool_Variable_1) == 0x000015, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, K2Node_Select_Default_1) == 0x000016, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_7) == 0x000017, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, Temp_byte_Variable_8) == 0x000018, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::Temp_byte_Variable_8' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor, K2Node_Select_Default_2) == 0x000019, "Member 'BPS28_LandingPageButton_C_ConvertWhiteTextToHoveredColor::K2Node_Select_Default_2' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.DetermineSelectedAnim
// 0x0010 (0x0010 - 0x0000)
struct BPS28_LandingPageButton_C_DetermineSelectedAnim final
{
public:
	bool                                          Hover;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidgetAnimation*                       ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_DetermineSelectedAnim) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_DetermineSelectedAnim");
static_assert(sizeof(BPS28_LandingPageButton_C_DetermineSelectedAnim) == 0x000010, "Wrong size on BPS28_LandingPageButton_C_DetermineSelectedAnim");
static_assert(offsetof(BPS28_LandingPageButton_C_DetermineSelectedAnim, Hover) == 0x000000, "Member 'BPS28_LandingPageButton_C_DetermineSelectedAnim::Hover' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_DetermineSelectedAnim, ReturnValue) == 0x000008, "Member 'BPS28_LandingPageButton_C_DetermineSelectedAnim::ReturnValue' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.ExecuteUbergraph_BPS28_LandingPageButton
// 0x03C0 (0x03C0 - 0x0000)
struct BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSound2D_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate;              // 0x001C(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              Temp_byte_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue_1;                 // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue_1;        // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue_2;                 // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue_2;        // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortMcpContext*                        CallFunc_GetContext_ReturnValue_3;                 // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UFortMcpProfileAthena*                  CallFunc_GetAthenaProfile_ReturnValue;             // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasPurchasedSeasonBook_ReturnValue;       // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_63[0x5];                                       // 0x0063(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_Event_Texture;                              // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_2;         // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue_4;                 // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_4;        // 0x009B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_5;        // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x009E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x009F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_6;        // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_7;        // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x00A3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue;  // 0x00A8(0x0070)(ConstParm)
	struct FBattlePassLandingPageButtonDisplayDetails K2Node_Event_NewDisplayDetails;                    // 0x0118(0x0070)(ConstParm)
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue_1; // 0x0188(0x0070)(ConstParm)
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue_2; // 0x01F8(0x0070)(ConstParm)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0269(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_ExtraLock;                      // 0x026A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x026B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x026C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26D[0x3];                                      // 0x026D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0278(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_289[0x7];                                      // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue_1;       // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0298(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       CallFunc_DetermineSelectedAnim_ReturnValue;        // 0x02A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       CallFunc_DetermineSelectedAnim_ReturnValue_1;      // 0x02A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x02B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x02B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B3[0x5];                                      // 0x02B3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue_3; // 0x02B8(0x0070)(ConstParm)
	bool                                          Temp_bool_Variable_2;                              // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstance*                      K2Node_Event_Material;                             // 0x0330(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_8;        // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_9;        // 0x0339(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_5;                  // 0x033A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Select_Default_1;                           // 0x033B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_6;                  // 0x033C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingTouch_ReturnValue;                 // 0x033D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_2;                           // 0x033E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_33F[0x1];                                      // 0x033F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue_4; // 0x0340(0x0070)(ConstParm)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x03B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUsingTouch_ReturnValue_1;               // 0x03B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B2[0x6];                                      // 0x03B2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x03B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton");
static_assert(sizeof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton) == 0x0003C0, "Wrong size on BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, EntryPoint) == 0x000000, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_SpawnSound2D_ReturnValue) == 0x000008, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_SpawnSound2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetContext_ReturnValue) == 0x000010, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetCurrentInputType_ReturnValue) == 0x000018, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_CreateDelegate_OutputDelegate) == 0x00001C, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable) == 0x000028, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_1) == 0x000029, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_2) == 0x00002A, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_3) == 0x00002B, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_4) == 0x00002C, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetContext_ReturnValue_1) == 0x000030, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetContext_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Select_Default) == 0x000038, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetCurrentInputType_ReturnValue_1) == 0x000039, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetCurrentInputType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetContext_ReturnValue_2) == 0x000040, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetContext_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000048, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetCurrentInputType_ReturnValue_2) == 0x000049, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetCurrentInputType_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x00004A, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetContext_ReturnValue_3) == 0x000050, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetContext_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetAthenaProfile_ReturnValue) == 0x000058, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetAthenaProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_bool_Variable) == 0x000060, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_HasPurchasedSeasonBook_ReturnValue) == 0x000061, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_HasPurchasedSeasonBook_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_bool_Variable_1) == 0x000062, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000068, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x000070, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_PlayAnimationForward_ReturnValue) == 0x000078, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Event_Texture) == 0x000080, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Event_Texture' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetDynamicMaterial_ReturnValue_2) == 0x000088, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetDynamicMaterial_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetContext_ReturnValue_4) == 0x000090, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetContext_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000098, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000099, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanAND_ReturnValue) == 0x00009A, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_4) == 0x00009B, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_5) == 0x00009C, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanAND_ReturnValue_1) == 0x00009D, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue) == 0x00009E, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_1) == 0x00009F, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_6) == 0x0000A0, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_7) == 0x0000A1, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanAND_ReturnValue_2) == 0x0000A2, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_2) == 0x0000A3, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetBattlePassDisplayDetails_ReturnValue) == 0x0000A8, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetBattlePassDisplayDetails_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Event_NewDisplayDetails) == 0x000118, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Event_NewDisplayDetails' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetBattlePassDisplayDetails_ReturnValue_1) == 0x000188, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetBattlePassDisplayDetails_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetBattlePassDisplayDetails_ReturnValue_2) == 0x0001F8, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetBattlePassDisplayDetails_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_TextIsEmpty_ReturnValue) == 0x000268, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_Not_PreBool_ReturnValue) == 0x000269, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_CustomEvent_ExtraLock) == 0x00026A, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_CustomEvent_ExtraLock' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_3) == 0x00026B, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_4) == 0x00026C, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000270, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_MakeVector2D_ReturnValue) == 0x000278, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_CustomEvent_bNewInputType) == 0x000288, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_CustomEvent_bNewInputType' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_PlayAnimationForward_ReturnValue_1) == 0x000290, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_PlayAnimationForward_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000298, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_DetermineSelectedAnim_ReturnValue) == 0x0002A0, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_DetermineSelectedAnim_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_DetermineSelectedAnim_ReturnValue_1) == 0x0002A8, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_DetermineSelectedAnim_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_5) == 0x0002B0, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_SwitchString_CmpSuccess) == 0x0002B1, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_SwitchString_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_byte_Variable_6) == 0x0002B2, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetBattlePassDisplayDetails_ReturnValue_3) == 0x0002B8, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetBattlePassDisplayDetails_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, Temp_bool_Variable_2) == 0x000328, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Event_Material) == 0x000330, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Event_Material' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_8) == 0x000338, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_EqualEqual_ByteByte_ReturnValue_9) == 0x000339, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_EqualEqual_ByteByte_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_5) == 0x00033A, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Select_Default_1) == 0x00033B, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_BooleanOR_ReturnValue_6) == 0x00033C, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_BooleanOR_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_IsUsingTouch_ReturnValue) == 0x00033D, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_IsUsingTouch_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Select_Default_2) == 0x00033E, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_GetBattlePassDisplayDetails_ReturnValue_4) == 0x000340, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_GetBattlePassDisplayDetails_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, K2Node_Event_IsDesignTime) == 0x0003B0, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_IsUsingTouch_ReturnValue_1) == 0x0003B1, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_IsUsingTouch_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0003B8, "Member 'BPS28_LandingPageButton_C_ExecuteUbergraph_BPS28_LandingPageButton::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.InputChanged
// 0x0001 (0x0001 - 0x0000)
struct BPS28_LandingPageButton_C_InputChanged final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_InputChanged) == 0x000001, "Wrong alignment on BPS28_LandingPageButton_C_InputChanged");
static_assert(sizeof(BPS28_LandingPageButton_C_InputChanged) == 0x000001, "Wrong size on BPS28_LandingPageButton_C_InputChanged");
static_assert(offsetof(BPS28_LandingPageButton_C_InputChanged, bNewInputType) == 0x000000, "Member 'BPS28_LandingPageButton_C_InputChanged::bNewInputType' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.IsCompetingButtonSelected
// 0x0050 (0x0050 - 0x0000)
struct BPS28_LandingPageButton_C_IsCompetingButtonSelected final
{
public:
	bool                                          Return;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        LocButtons;                                        // 0x0008(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBPS28_LandingPageButton_C*             K2Node_DynamicCast_AsBPS28_Landing_Page_Button;    // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_IsCompetingButtonSelected) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_IsCompetingButtonSelected");
static_assert(sizeof(BPS28_LandingPageButton_C_IsCompetingButtonSelected) == 0x000050, "Wrong size on BPS28_LandingPageButton_C_IsCompetingButtonSelected");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, Return) == 0x000000, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::Return' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, LocButtons) == 0x000008, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::LocButtons' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, Temp_int_Array_Index_Variable) == 0x000018, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, CallFunc_Array_Get_Item) == 0x000028, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, CallFunc_Array_RemoveItem_ReturnValue) == 0x000030, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, K2Node_DynamicCast_AsBPS28_Landing_Page_Button) == 0x000038, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::K2Node_DynamicCast_AsBPS28_Landing_Page_Button' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, K2Node_DynamicCast_bSuccess) == 0x000040, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, CallFunc_Array_Length_ReturnValue) == 0x000044, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_IsCompetingButtonSelected, CallFunc_Less_IntInt_ReturnValue) == 0x000048, "Member 'BPS28_LandingPageButton_C_IsCompetingButtonSelected::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.OnDisplayDetailsUpdated
// 0x0070 (0x0070 - 0x0000)
struct BPS28_LandingPageButton_C_OnDisplayDetailsUpdated final
{
public:
	struct FBattlePassLandingPageButtonDisplayDetails NewDisplayDetails;                                 // 0x0000(0x0070)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BPS28_LandingPageButton_C_OnDisplayDetailsUpdated) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_OnDisplayDetailsUpdated");
static_assert(sizeof(BPS28_LandingPageButton_C_OnDisplayDetailsUpdated) == 0x000070, "Wrong size on BPS28_LandingPageButton_C_OnDisplayDetailsUpdated");
static_assert(offsetof(BPS28_LandingPageButton_C_OnDisplayDetailsUpdated, NewDisplayDetails) == 0x000000, "Member 'BPS28_LandingPageButton_C_OnDisplayDetailsUpdated::NewDisplayDetails' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.OnSetTileImageMaterial
// 0x0008 (0x0008 - 0x0000)
struct BPS28_LandingPageButton_C_OnSetTileImageMaterial final
{
public:
	class UMaterialInstance*                      Material_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_OnSetTileImageMaterial) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_OnSetTileImageMaterial");
static_assert(sizeof(BPS28_LandingPageButton_C_OnSetTileImageMaterial) == 0x000008, "Wrong size on BPS28_LandingPageButton_C_OnSetTileImageMaterial");
static_assert(offsetof(BPS28_LandingPageButton_C_OnSetTileImageMaterial, Material_0) == 0x000000, "Member 'BPS28_LandingPageButton_C_OnSetTileImageMaterial::Material_0' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.OnSubscriptionTextureLoaded
// 0x0008 (0x0008 - 0x0000)
struct BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded final
{
public:
	class UTexture2D*                             Texture;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded");
static_assert(sizeof(BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded) == 0x000008, "Wrong size on BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded");
static_assert(offsetof(BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded, Texture) == 0x000000, "Member 'BPS28_LandingPageButton_C_OnSubscriptionTextureLoaded::Texture' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BPS28_LandingPageButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_PreConstruct) == 0x000001, "Wrong alignment on BPS28_LandingPageButton_C_PreConstruct");
static_assert(sizeof(BPS28_LandingPageButton_C_PreConstruct) == 0x000001, "Wrong size on BPS28_LandingPageButton_C_PreConstruct");
static_assert(offsetof(BPS28_LandingPageButton_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'BPS28_LandingPageButton_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.SetExtraLock
// 0x0001 (0x0001 - 0x0000)
struct BPS28_LandingPageButton_C_SetExtraLock final
{
public:
	bool                                          ExtraLock;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_SetExtraLock) == 0x000001, "Wrong alignment on BPS28_LandingPageButton_C_SetExtraLock");
static_assert(sizeof(BPS28_LandingPageButton_C_SetExtraLock) == 0x000001, "Wrong size on BPS28_LandingPageButton_C_SetExtraLock");
static_assert(offsetof(BPS28_LandingPageButton_C_SetExtraLock, ExtraLock) == 0x000000, "Member 'BPS28_LandingPageButton_C_SetExtraLock::ExtraLock' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.UnHoverOtherLandingPageButtons
// 0x0040 (0x0040 - 0x0000)
struct BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons final
{
public:
	TArray<class UWidget*>                        LocButtons;                                        // 0x0000(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBPS28_LandingPageButton_C*             K2Node_DynamicCast_AsBPS28_Landing_Page_Button;    // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons");
static_assert(sizeof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons) == 0x000040, "Wrong size on BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, LocButtons) == 0x000000, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::LocButtons' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, Temp_int_Array_Index_Variable) == 0x000010, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, CallFunc_Array_Get_Item) == 0x000020, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, K2Node_DynamicCast_AsBPS28_Landing_Page_Button) == 0x000028, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::K2Node_DynamicCast_AsBPS28_Landing_Page_Button' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, CallFunc_Array_Length_ReturnValue) == 0x000034, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons, CallFunc_Array_RemoveItem_ReturnValue) == 0x000039, "Member 'BPS28_LandingPageButton_C_UnHoverOtherLandingPageButtons::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");

// Function BPS28_LandingPageButton.BPS28_LandingPageButton_C.UpdateDisplayBehaviorFromData
// 0x02B0 (0x02B0 - 0x0000)
struct BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData final
{
public:
	struct FBattlePassLandingPageButtonDisplayBehaviorData BehaviorData;                                      // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	bool                                          bIsDisplayActive;                                  // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimespan                              BehaviorTimespan;                                  // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              ButtonUnlockDelay;                                 // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetTotalSeconds_ReturnValue;              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetTotalSeconds_ReturnValue_1;            // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetTimespanAsText_ReturnValue;            // 0x0048(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0060(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00B0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00C0(0x0018)()
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetTimespanAsText_ReturnValue_1;          // 0x00E0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00F8(0x0050)(HasGetValueTypeHash)
	int32                                         CallFunc_GetDays_ReturnValue;                      // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14C[0x4];                                      // 0x014C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0150(0x0010)(ReferenceParm)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0168(0x0018)()
	class FText                                   CallFunc_GetTimespanAsText_ReturnValue_2;          // 0x0180(0x0018)()
	int32                                         CallFunc_GetDays_ReturnValue_1;                    // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x01A0(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F1[0x7];                                      // 0x01F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x01F8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x0208(0x0018)()
	float                                         CallFunc_GetTotalSeconds_ReturnValue_2;            // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_2;       // 0x0224(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_225[0x3];                                      // 0x0225(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBattlePassLandingPageButtonDisplayDetails CallFunc_GetBattlePassDisplayDetails_ReturnValue;  // 0x0228(0x0070)(ConstParm)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast_1;    // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast_2;    // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData) == 0x000008, "Wrong alignment on BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData");
static_assert(sizeof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData) == 0x0002B0, "Wrong size on BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, BehaviorData) == 0x000000, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::BehaviorData' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, bIsDisplayActive) == 0x000018, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::bIsDisplayActive' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, BehaviorTimespan) == 0x000020, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::BehaviorTimespan' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, ButtonUnlockDelay) == 0x000028, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::ButtonUnlockDelay' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_SwitchEnum_CmpSuccess) == 0x000030, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTotalSeconds_ReturnValue) == 0x000034, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTotalSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000038, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTotalSeconds_ReturnValue_1) == 0x00003C, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTotalSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_ReturnValue_1) == 0x000040, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTimespanAsText_ReturnValue) == 0x000048, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTimespanAsText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeStruct_FormatArgumentData) == 0x000060, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeArray_Array) == 0x0000B0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Format_ReturnValue) == 0x0000C0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_BooleanAND_ReturnValue) == 0x0000D8, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTimespanAsText_ReturnValue_1) == 0x0000E0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTimespanAsText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000F8, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetDays_ReturnValue) == 0x000148, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetDays_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeArray_Array_1) == 0x000150, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000160, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Format_ReturnValue_1) == 0x000168, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTimespanAsText_ReturnValue_2) == 0x000180, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTimespanAsText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetDays_ReturnValue_1) == 0x000198, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetDays_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeStruct_FormatArgumentData_2) == 0x0001A0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x0001F0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, K2Node_MakeArray_Array_2) == 0x0001F8, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Format_ReturnValue_2) == 0x000208, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Format_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetTotalSeconds_ReturnValue_2) == 0x000220, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetTotalSeconds_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_ReturnValue_2) == 0x000224, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_GetBattlePassDisplayDetails_ReturnValue) == 0x000228, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_GetBattlePassDisplayDetails_ReturnValue' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000298, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_A_ImplicitCast_1) == 0x0002A0, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData, CallFunc_Greater_DoubleDouble_A_ImplicitCast_2) == 0x0002A8, "Member 'BPS28_LandingPageButton_C_UpdateDisplayBehaviorFromData::CallFunc_Greater_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");

}

