#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseQuery_0

#include "Basic.hpp"

#include "VerseQuery_0_classes.hpp"
#include "VerseQuery_0_parameters.hpp"


namespace SDK
{

// Function VerseQuery.VerseQuery_playspace_association_component.$Block
// ()

void UVerseQuery_playspace_association_component::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_playspace_association_component.$InitCDO
// ()

void UVerseQuery_playspace_association_component::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_playspace_association_component.$InitInstance
// ()

void UVerseQuery_playspace_association_component::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfType_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TArray<class UEntity_core_entity*>      RetVal                                                 (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UEntity_core_entity*> UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfType_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfType_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfType_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfTypeIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UObject*                          RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UObject* UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfTypeIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfTypeIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesOfTypeIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NEntityClass_20where_20EntityClass_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponents_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity__component_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TArray<class UEntity_core_entity*>      RetVal                                                 (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UEntity_core_entity*> UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponents_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity__component_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponents_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponents_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponentsIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UObject*                          RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UObject* UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponentsIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mcore__entity_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponentsIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithComponentsIterator_U_L_Nquery__manager_M_Ntuple_L_R_M_NComponentClass_20where_20ComponentClass_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithinVolume_U_L_Nquery__manager_M_Ntuple_L_R_M_Nquery__volume_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mquery__volume_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TArray<class UEntity_core_entity*>      RetVal                                                 (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UEntity_core_entity*> UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithinVolume_U_L_Nquery__manager_M_Ntuple_L_R_M_Nquery__volume_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mquery__volume_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithinVolume_U_L_Nquery__manager_M_Ntuple_L_R_M_Nquery__volume_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithinVolume_U_L_Nquery__manager_M_Ntuple_L_R_M_Nquery__volume_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithTags_U_L_Nquery__manager_M_Ntuple_L_R_M_Ntuple_L_Ktag_M_Ktag_M_Ktag_R_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lquery__manager_Mtuple_L_R_Mtuple_L_Ktag_M_Ktag_M_Ktag_R_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TArray<class UEntity_core_entity*>      RetVal                                                 (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UEntity_core_entity*> UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithTags_U_L_Nquery__manager_M_Ntuple_L_R_M_Ntuple_L_Ktag_M_Ktag_M_Ktag_R_R(const struct Ftuple_Lquery__manager_Mtuple_L_R_Mtuple_L_Ktag_M_Ktag_M_Ktag_R_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithTags_U_L_Nquery__manager_M_Ntuple_L_R_M_Ntuple_L_Ktag_M_Ktag_M_Ktag_R_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eEntitiesWithTags_U_L_Nquery__manager_M_Ntuple_L_R_M_Ntuple_L_Ktag_M_Ktag_M_Ktag_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncomponent_M_Ntuple_L_R_M_Ntuple_L_R_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lcomponent_Mtuple_L_R_Mtuple_L_R_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UEntityQueryManager*              RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UEntityQueryManager* UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncomponent_M_Ntuple_L_R_M_Ntuple_L_R_R(const struct Ftuple_Lcomponent_Mtuple_L_R_Mtuple_L_R_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncomponent_M_Ntuple_L_R_M_Ntuple_L_R_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncomponent_M_Ntuple_L_R_M_Ntuple_L_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity__component_M_Ntuple_L_R_M_Ntuple_L_R_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lcore__entity__component_Mtuple_L_R_Mtuple_L_R_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UEntityQueryManager*              RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UEntityQueryManager* UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity__component_M_Ntuple_L_R_M_Ntuple_L_R_R(const struct Ftuple_Lcore__entity__component_Mtuple_L_R_Mtuple_L_R_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity__component_M_Ntuple_L_R_M_Ntuple_L_R_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity__component_M_Ntuple_L_R_M_Ntuple_L_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery._L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity_M_Ntuple_L_R_M_Ntuple_L_R_R
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct Ftuple_Lcore__entity_Mtuple_L_R_Mtuple_L_R_R__verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UEntityQueryManager*              RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UEntityQueryManager* UVerseQuery::_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity_M_Ntuple_L_R_M_Ntuple_L_R_R(const struct Ftuple_Lcore__entity_Mtuple_L_R_Mtuple_L_R_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity_M_Ntuple_L_R_M_Ntuple_L_R_R");

	Params::VerseQuery__L_2fUnrealEngine_2ecom_2fVerseQuery_N_Roperator_U_2eGetQueryManager_U_L_Ncore__entity_M_Ntuple_L_R_M_Ntuple_L_R_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery.$InitCDO
// ()

void UVerseQuery::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid
// (Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UVerseQuery_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid");

	Params::VerseQuery_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext
// (Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TOptional<class UEntity_core_entity*, true>RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)

TOptional<class UEntity_core_entity*, true> UVerseQuery_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext");

	Params::VerseQuery_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_core_entity_query_iterator.$Block
// ()

void UVerseQuery_core_entity_query_iterator::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_core_entity_query_iterator.$InitCDO
// ()

void UVerseQuery_core_entity_query_iterator::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_core_entity_query_iterator.$InitInstance
// ()

void UVerseQuery_core_entity_query_iterator::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_core_entity_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UVerseQuery_core_entity_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid");

	Params::VerseQuery_core_entity_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_core_entity_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TOptional<class UEntity_core_entity*, true>RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)

TOptional<class UEntity_core_entity*, true> UVerseQuery_core_entity_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext");

	Params::VerseQuery_core_entity_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_null_query_iterator.$Block
// ()

void UVerseQuery_null_query_iterator::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_null_query_iterator.$InitCDO
// ()

void UVerseQuery_null_query_iterator::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_null_query_iterator.$InitInstance
// ()

void UVerseQuery_null_query_iterator::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_null_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UVerseQuery_null_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid");

	Params::VerseQuery_null_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RIsValid Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_null_query_iterator._L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// TOptional<class UEntity_core_entity*, true>RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, ContainsInstancedReference, HasGetValueTypeHash)

TOptional<class UEntity_core_entity*, true> UVerseQuery_null_query_iterator::_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext");

	Params::VerseQuery_null_query_iterator__L_2fUnrealEngine_2ecom_2fVerseQuery_2fquery__iterator_N_RNext Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_query_volume.$Block
// ()

void UVerseQuery_query_volume::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_volume.$InitCDO
// ()

void UVerseQuery_query_volume::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_volume.$InitInstance
// ()

void UVerseQuery_query_volume::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_volume_box.$Block
// ()

void UVerseQuery_query_volume_box::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_volume_box.$InitCDO
// (HasDefaults)

void UVerseQuery_query_volume_box::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_query_volume_box.$InitInstance
// ()

void UVerseQuery_query_volume_box::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component.$Block
// ()

void UVerseQuery_tag_container_core_entity_component::_Block()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component.$InitCDO
// (HasDefaults)

void UVerseQuery_tag_container_core_entity_component::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component.$InitInstance
// ()

void UVerseQuery_tag_container_core_entity_component::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RAddedToWorld
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RAddedToWorld(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RAddedToWorld");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RAddedToWorld Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RRemovingFromWorld
// (Native, Public, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)

void UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RRemovingFromWorld(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RRemovingFromWorld");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fEntityFramework_2fEntity_2fcore__entity__component_N_RRemovingFromWorld Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RAddTag_L_Ntag_R
// (Native, Public, BlueprintCallable)
// Parameters:
// class UTags_tag*                        __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RAddTag_L_Ntag_R(class UTags_tag* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RAddTag_L_Ntag_R");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RAddTag_L_Ntag_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RGetTags
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct VerseQuery_0::Ftuple_L_R         __verse_0xB2CDDD72_Argument                            (Parm, HasGetValueTypeHash)
// class UTags_tag_container*              RetVal                                                 (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

class UTags_tag_container* UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RGetTags(const struct VerseQuery_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RGetTags");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RGetTags Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RRemoveTag_L_Ntag_R
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UTags_tag*                        __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
// uint8                                   RetVal                                                 (Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash)

uint8 UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RRemoveTag_L_Ntag_R(class UTags_tag* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RRemoveTag_L_Ntag_R");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RRemoveTag_L_Ntag_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseQuery.VerseQuery_tag_container_core_entity_component._L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RSetTags_L_Ntag__container_R
// (Native, Public, BlueprintCallable)
// Parameters:
// class UTags_tag_container*              __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void UVerseQuery_tag_container_core_entity_component::_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RSetTags_L_Ntag__container_R(class UTags_tag_container* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("_L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RSetTags_L_Ntag__container_R");

	Params::VerseQuery_tag_container_core_entity_component__L_2fUnrealEngine_2ecom_2fVerseQuery_2ftag__container__core__entity__component_N_RSetTags_L_Ntag__container_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}

}

