#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ActiveAugments_List

#include "Basic.hpp"

#include "WBP_ActiveAugments_List_classes.hpp"
#include "WBP_ActiveAugments_List_parameters.hpp"


namespace SDK
{

// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.CreateActiveAugmentList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::CreateActiveAugmentList(int32 Count)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CreateActiveAugmentList");

	Params::WBP_ActiveAugments_List_C_CreateActiveAugmentList Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.ExecuteUbergraph_WBP_ActiveAugments_List
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::ExecuteUbergraph_WBP_ActiveAugments_List(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_WBP_ActiveAugments_List");

	Params::WBP_ActiveAugments_List_C_ExecuteUbergraph_WBP_ActiveAugments_List Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.OnActiveListOpened
// (BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::OnActiveListOpened()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnActiveListOpened");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.OnAugmentsUpdated
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// TArray<class UFortPlayerAugmentItemDefinition*>ActiveAugments                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ActiveAugments_List_C::OnAugmentsUpdated(const TArray<class UFortPlayerAugmentItemDefinition*>& ActiveAugments)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnAugmentsUpdated");

	Params::WBP_ActiveAugments_List_C_OnAugmentsUpdated Parms{};

	Parms.ActiveAugments = std::move(ActiveAugments);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::WBP_ActiveAugments_List_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.RefreshArrows
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::RefreshArrows()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RefreshArrows");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.RefreshCurrentAugmentList
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::RefreshCurrentAugmentList()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RefreshCurrentAugmentList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.ResetFocusedEntry
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::ResetFocusedEntry()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ResetFocusedEntry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.ScrollDown
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::ScrollDown()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ScrollDown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.ScrollUp
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ActiveAugments_List_C::ScrollUp()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ScrollUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.SetFocusedEntry
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewFocusedEntryIndex                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::SetFocusedEntry(int32 NewFocusedEntryIndex)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetFocusedEntry");

	Params::WBP_ActiveAugments_List_C_SetFocusedEntry Parms{};

	Parms.NewFocusedEntryIndex = NewFocusedEntryIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.UpdateScrollBoundAction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        InputType_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::UpdateScrollBoundAction(ECommonInputType InputType_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateScrollBoundAction");

	Params::WBP_ActiveAugments_List_C_UpdateScrollBoundAction Parms{};

	Parms.InputType_0 = InputType_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ActiveAugments_List.WBP_ActiveAugments_List_C.GetNumAugmentGrantRounds
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   NumAugmentsForRound                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ActiveAugments_List_C::GetNumAugmentGrantRounds(int32* NumAugmentsForRound) const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetNumAugmentGrantRounds");

	Params::WBP_ActiveAugments_List_C_GetNumAugmentGrantRounds Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NumAugmentsForRound != nullptr)
		*NumAugmentsForRound = Parms.NumAugmentsForRound;
}

}

