#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemShopTile_Base

#include "Basic.hpp"

#include "WBP_ItemShopTile_Base_classes.hpp"
#include "WBP_ItemShopTile_Base_parameters.hpp"


namespace SDK
{

// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.ClearTimers
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::ClearTimers()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ClearTimers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.CreatePriceSwitcher
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::CreatePriceSwitcher()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CreatePriceSwitcher");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.CreateTagRotator
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::CreateTagRotator()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CreateTagRotator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.CreateViolator
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::CreateViolator()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CreateViolator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.ExecuteUbergraph_WBP_ItemShopTile_Base
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::ExecuteUbergraph_WBP_ItemShopTile_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_WBP_ItemShopTile_Base");

	Params::WBP_ItemShopTile_Base_C_ExecuteUbergraph_WBP_ItemShopTile_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.Finished_F67CBD49492AADE02541788EA696B3BA
// (BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::Finished_F67CBD49492AADE02541788EA696B3BA()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Finished_F67CBD49492AADE02541788EA696B3BA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.GetNextPresentationIndex
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UWBP_ItemShopTile_Base_C::GetNextPresentationIndex()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetNextPresentationIndex");

	Params::WBP_ItemShopTile_Base_C_GetNextPresentationIndex Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.GetTileAnchor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector2D                        PixelPosition                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::GetTileAnchor(struct FVector2D* PixelPosition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetTileAnchor");

	Params::WBP_ItemShopTile_Base_C_GetTileAnchor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PixelPosition != nullptr)
		*PixelPosition = std::move(Parms.PixelPosition);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.HandleInputMethodChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        bNewInputType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::HandleInputMethodChanged(ECommonInputType bNewInputType)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleInputMethodChanged");

	Params::WBP_ItemShopTile_Base_C_HandleInputMethodChanged Parms{};

	Parms.bNewInputType = bNewInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.HandleNoLoadedPresentations
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::HandleNoLoadedPresentations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleNoLoadedPresentations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.HideOfferDetails
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsImmediate                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::HideOfferDetails(bool IsImmediate)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HideOfferDetails");

	Params::WBP_ItemShopTile_Base_C_HideOfferDetails Parms{};

	Parms.IsImmediate = IsImmediate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.InitializeMaterials
// (Protected, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::InitializeMaterials()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.InitializeTile
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::InitializeTile()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeTile");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.InitializeVisualState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        CurrentInputType                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::InitializeVisualState(ECommonInputType CurrentInputType)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeVisualState");

	Params::WBP_ItemShopTile_Base_C_InitializeVisualState Parms{};

	Parms.CurrentInputType = CurrentInputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.IsMobileFrontend
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsMobileFrontend                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::IsMobileFrontend(bool* bIsMobileFrontend)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("IsMobileFrontend");

	Params::WBP_ItemShopTile_Base_C_IsMobileFrontend Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsMobileFrontend != nullptr)
		*bIsMobileFrontend = Parms.bIsMobileFrontend;
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_ItemShopTile_Base_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnAddedToFocusPath");

	Params::WBP_ItemShopTile_Base_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.OnHandlePresentations
// (BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::OnHandlePresentations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnHandlePresentations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.OnPresentationSwap
// (BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::OnPresentationSwap()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPresentationSwap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::WBP_ItemShopTile_Base_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.Set Unfocused Hover
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    OnlyResetAnimation                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::Set_Unfocused_Hover(bool IsHovered_0, bool OnlyResetAnimation)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Set Unfocused Hover");

	Params::WBP_ItemShopTile_Base_C_Set_Unfocused_Hover Parms{};

	Parms.IsHovered_0 = IsHovered_0;
	Parms.OnlyResetAnimation = OnlyResetAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetActiveState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsActiveState                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetActiveState(bool IsActiveState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetActiveState");

	Params::WBP_ItemShopTile_Base_C_SetActiveState Parms{};

	Parms.IsActiveState = IsActiveState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetBottomInfoActiveWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_PriceSwitcherState                    PriceSwitcherState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetBottomInfoActiveWidget(E_PriceSwitcherState PriceSwitcherState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetBottomInfoActiveWidget");

	Params::WBP_ItemShopTile_Base_C_SetBottomInfoActiveWidget Parms{};

	Parms.PriceSwitcherState = PriceSwitcherState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetCurrency
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EItemShopCurrency                       CurrencyType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetCurrency(EItemShopCurrency CurrencyType)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetCurrency");

	Params::WBP_ItemShopTile_Base_C_SetCurrency Parms{};

	Parms.CurrencyType = CurrencyType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetDescriptionOffsetAnimValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetDescriptionOffsetAnimValue(double Value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetDescriptionOffsetAnimValue");

	Params::WBP_ItemShopTile_Base_C_SetDescriptionOffsetAnimValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetDescriptionVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visibility_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetDescriptionVisibility(ESlateVisibility Visibility_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetDescriptionVisibility");

	Params::WBP_ItemShopTile_Base_C_SetDescriptionVisibility Parms{};

	Parms.Visibility_0 = Visibility_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetHoveredState
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::SetHoveredState()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetHoveredState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetHoveredStateVisual
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsHovered_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetHoveredStateVisual(bool IsHovered_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetHoveredStateVisual");

	Params::WBP_ItemShopTile_Base_C_SetHoveredStateVisual Parms{};

	Parms.IsHovered_0 = IsHovered_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetOfferDescription
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ItemShopTile_Base_C::SetOfferDescription(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetOfferDescription");

	Params::WBP_ItemShopTile_Base_C_SetOfferDescription Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetOfferMaterial
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TDelegate<void()>                       PresentationSwapDelegate                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetOfferMaterial(TDelegate<void()> PresentationSwapDelegate)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetOfferMaterial");

	Params::WBP_ItemShopTile_Base_C_SetOfferMaterial Parms{};

	Parms.PresentationSwapDelegate = PresentationSwapDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetOfferName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ItemShopTile_Base_C::SetOfferName(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetOfferName");

	Params::WBP_ItemShopTile_Base_C_SetOfferName Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetOfferNameTextLayout
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::SetOfferNameTextLayout()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetOfferNameTextLayout");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetPeekState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsInPeekState_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetPeekState(bool IsInPeekState_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPeekState");

	Params::WBP_ItemShopTile_Base_C_SetPeekState Parms{};

	Parms.IsInPeekState_0 = IsInPeekState_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetPresentations
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UMaterialInterface*>       Presentations_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ItemShopTile_Base_C::SetPresentations(TArray<class UMaterialInterface*>& Presentations_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPresentations");

	Params::WBP_ItemShopTile_Base_C_SetPresentations Parms{};

	Parms.Presentations_0 = std::move(Presentations_0);

	UObject::ProcessEvent(Func, &Parms);

	Presentations_0 = std::move(Parms.Presentations_0);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetPresentationsLoadingState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsLoading                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ShouldClearPresentationsArray                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetPresentationsLoadingState(bool IsLoading, bool ShouldClearPresentationsArray)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPresentationsLoadingState");

	Params::WBP_ItemShopTile_Base_C_SetPresentationsLoadingState Parms{};

	Parms.IsLoading = IsLoading;
	Parms.ShouldClearPresentationsArray = ShouldClearPresentationsArray;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetPreviewData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Description                                            (BlueprintVisible, BlueprintReadOnly, Parm)
// ESlateVisibility                        DescriptionVisibility                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EItemShopTileSize                       TileSize_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFortColorPalette                RarityColor_0                                          (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// TArray<class UMaterialInterface*>       Presentations_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   Price_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RegularPrice_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EItemShopCurrency                       Currency_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_PriceSwitcherState                    PriceState                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ViolatorText_0                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// EViolatorIntensity                      ViolatorIntensity_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class FText>                     TagTexts_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ItemShopTile_Base_C::SetPreviewData(const class FText& Name_0, const class FText& Description, ESlateVisibility DescriptionVisibility, EItemShopTileSize TileSize_0, const struct FFortColorPalette& RarityColor_0, TArray<class UMaterialInterface*>& Presentations_0, int32 Price_0, int32 RegularPrice_0, EItemShopCurrency Currency_0, E_PriceSwitcherState PriceState, const class FText& ViolatorText_0, EViolatorIntensity ViolatorIntensity_0, TArray<class FText>& TagTexts_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPreviewData");

	Params::WBP_ItemShopTile_Base_C_SetPreviewData Parms{};

	Parms.Name_0 = std::move(Name_0);
	Parms.Description = std::move(Description);
	Parms.DescriptionVisibility = DescriptionVisibility;
	Parms.TileSize_0 = TileSize_0;
	Parms.RarityColor_0 = std::move(RarityColor_0);
	Parms.Presentations_0 = std::move(Presentations_0);
	Parms.Price_0 = Price_0;
	Parms.RegularPrice_0 = RegularPrice_0;
	Parms.Currency_0 = Currency_0;
	Parms.PriceState = PriceState;
	Parms.ViolatorText_0 = std::move(ViolatorText_0);
	Parms.ViolatorIntensity_0 = ViolatorIntensity_0;
	Parms.TagTexts_0 = std::move(TagTexts_0);

	UObject::ProcessEvent(Func, &Parms);

	Presentations_0 = std::move(Parms.Presentations_0);
	TagTexts_0 = std::move(Parms.TagTexts_0);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetPrice
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ItemShopTile_Base_C::SetPrice(const class FText& Value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPrice");

	Params::WBP_ItemShopTile_Base_C_SetPrice Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetRarityStripColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFortColorPalette                Color                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_ItemShopTile_Base_C::SetRarityStripColor(const struct FFortColorPalette& Color)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetRarityStripColor");

	Params::WBP_ItemShopTile_Base_C_SetRarityStripColor Parms{};

	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetRegularPrice
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ItemShopTile_Base_C::SetRegularPrice(const class FText& Value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetRegularPrice");

	Params::WBP_ItemShopTile_Base_C_SetRegularPrice Parms{};

	Parms.Value = std::move(Value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetRegularPriceVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetRegularPriceVisibility(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetRegularPriceVisibility");

	Params::WBP_ItemShopTile_Base_C_SetRegularPriceVisibility Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetRimBrushColor
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActionWidget*              IconRim                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetRimBrushColor(class UCommonActionWidget* IconRim, const struct FLinearColor& Color)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetRimBrushColor");

	Params::WBP_ItemShopTile_Base_C_SetRimBrushColor Parms{};

	Parms.IconRim = IconRim;
	Parms.Color = std::move(Color);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetSubInfoText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             SubInfoText                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_ItemShopTile_Base_C::SetSubInfoText(const class FText& SubInfoText)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetSubInfoText");

	Params::WBP_ItemShopTile_Base_C_SetSubInfoText Parms{};

	Parms.SubInfoText = std::move(SubInfoText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetTagOffsetAnimValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetTagOffsetAnimValue(double Value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetTagOffsetAnimValue");

	Params::WBP_ItemShopTile_Base_C_SetTagOffsetAnimValue Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetTagTexts
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FText>                     TagTexts_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ItemShopTile_Base_C::SetTagTexts(TArray<class FText>& TagTexts_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetTagTexts");

	Params::WBP_ItemShopTile_Base_C_SetTagTexts Parms{};

	Parms.TagTexts_0 = std::move(TagTexts_0);

	UObject::ProcessEvent(Func, &Parms);

	TagTexts_0 = std::move(Parms.TagTexts_0);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetTileSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector2D                        TileSize_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetTileSize(const struct FVector2D& TileSize_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetTileSize");

	Params::WBP_ItemShopTile_Base_C_SetTileSize Parms{};

	Parms.TileSize_0 = std::move(TileSize_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetUnhoveredState
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::SetUnhoveredState()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetUnhoveredState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetupModularBlocks
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::SetupModularBlocks()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetupModularBlocks");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetViolatorIntensity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EViolatorIntensity                      ViolatorIntensity_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::SetViolatorIntensity(EViolatorIntensity ViolatorIntensity_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetViolatorIntensity");

	Params::WBP_ItemShopTile_Base_C_SetViolatorIntensity Parms{};

	Parms.ViolatorIntensity_0 = ViolatorIntensity_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.SetViolatorText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_ItemShopTile_Base_C::SetViolatorText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetViolatorText");

	Params::WBP_ItemShopTile_Base_C_SetViolatorText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.ShowOfferDetails
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsImmediate                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::ShowOfferDetails(bool IsImmediate)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ShowOfferDetails");

	Params::WBP_ItemShopTile_Base_C_ShowOfferDetails Parms{};

	Parms.IsImmediate = IsImmediate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.UpdateGradientHeight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Mid                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::UpdateGradientHeight(class UMaterialInstanceDynamic* Mid)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateGradientHeight");

	Params::WBP_ItemShopTile_Base_C_UpdateGradientHeight Parms{};

	Parms.Mid = Mid;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.UpdateImagesPresentations
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_ItemShopTile_Base_C::UpdateImagesPresentations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateImagesPresentations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.UpdateItemLivePreview
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortThumbnailRenderer*           ThumbnailRendererPtr                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AFortItemCaptureActor*            CaptureActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::UpdateItemLivePreview(class UFortThumbnailRenderer* ThumbnailRendererPtr, class AFortItemCaptureActor* CaptureActor)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateItemLivePreview");

	Params::WBP_ItemShopTile_Base_C_UpdateItemLivePreview Parms{};

	Parms.ThumbnailRendererPtr = ThumbnailRendererPtr;
	Parms.CaptureActor = CaptureActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.GetPriceFormattedText
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Price_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EItemShopCurrency                       Currency_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           CurrencySubType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FText                             PriceText                                              (Parm, OutParm)

void UWBP_ItemShopTile_Base_C::GetPriceFormattedText(int32 Price_0, EItemShopCurrency Currency_0, const class FString& CurrencySubType, class FText* PriceText) const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetPriceFormattedText");

	Params::WBP_ItemShopTile_Base_C_GetPriceFormattedText Parms{};

	Parms.Price_0 = Price_0;
	Parms.Currency_0 = Currency_0;
	Parms.CurrencySubType = std::move(CurrencySubType);

	UObject::ProcessEvent(Func, &Parms);

	if (PriceText != nullptr)
		*PriceText = std::move(Parms.PriceText);
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.GetStrikethroughPriceVisibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   Price_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RegularPrice_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    SuppressStrikethrough                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESlateVisibility                        StrikethroughPriceVisibility                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::GetStrikethroughPriceVisibility(int32 Price_0, int32 RegularPrice_0, bool SuppressStrikethrough, ESlateVisibility* StrikethroughPriceVisibility) const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetStrikethroughPriceVisibility");

	Params::WBP_ItemShopTile_Base_C_GetStrikethroughPriceVisibility Parms{};

	Parms.Price_0 = Price_0;
	Parms.RegularPrice_0 = RegularPrice_0;
	Parms.SuppressStrikethrough = SuppressStrikethrough;

	UObject::ProcessEvent(Func, &Parms);

	if (StrikethroughPriceVisibility != nullptr)
		*StrikethroughPriceVisibility = Parms.StrikethroughPriceVisibility;
}


// Function WBP_ItemShopTile_Base.WBP_ItemShopTile_Base_C.HasTransference
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TSet<ECosmeticCompatibleMode>           CompatibleModes                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    HasTransference_0                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ItemShopTile_Base_C::HasTransference(const TSet<ECosmeticCompatibleMode>& CompatibleModes, bool* HasTransference_0) const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HasTransference");

	Params::WBP_ItemShopTile_Base_C_HasTransference Parms{};

	Parms.CompatibleModes = std::move(CompatibleModes);

	UObject::ProcessEvent(Func, &Parms);

	if (HasTransference_0 != nullptr)
		*HasTransference_0 = Parms.HasTransference_0;
}

}

