#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Mobile_Augment_SelectionTimer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PlayerAugmentsUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Mobile_Augment_SelectionTimer.WBP_Mobile_Augment_SelectionTimer_C
// 0x0010 (0x0380 - 0x0370)
class UWBP_Mobile_Augment_SelectionTimer_C final : public UFortMobilePlayerAugmentTimer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Augment_SelectionTimer_C*          WBP_Augment_SelectionTimer_34;                     // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnHUDElementVisibilityChanged(const struct FGameplayTagContainer& HiddenElementTagContainer, bool bIsSelectionItemEquipped, bool bForceCollapse);
	void ExecuteUbergraph_WBP_Mobile_Augment_SelectionTimer(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Mobile_Augment_SelectionTimer_C">();
	}
	static class UWBP_Mobile_Augment_SelectionTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Mobile_Augment_SelectionTimer_C>();
	}
};
static_assert(alignof(UWBP_Mobile_Augment_SelectionTimer_C) == 0x000008, "Wrong alignment on UWBP_Mobile_Augment_SelectionTimer_C");
static_assert(sizeof(UWBP_Mobile_Augment_SelectionTimer_C) == 0x000380, "Wrong size on UWBP_Mobile_Augment_SelectionTimer_C");
static_assert(offsetof(UWBP_Mobile_Augment_SelectionTimer_C, UberGraphFrame) == 0x000370, "Member 'UWBP_Mobile_Augment_SelectionTimer_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Mobile_Augment_SelectionTimer_C, WBP_Augment_SelectionTimer_34) == 0x000378, "Member 'UWBP_Mobile_Augment_SelectionTimer_C::WBP_Augment_SelectionTimer_34' has a wrong offset!");

}

